---

- name: "copy consul bin file"
  copy: 
    src: consul
    dest: /usr/local/bin/consul
    mode: 0755

- name: "set systemd service file"
  template:
    src: consul.service.template
    dest: /etc/systemd/system/consul.service

- name: "mkdir /etc/sysconfig"
  file:
    path: /etc/sysconfig
    state: directory

- name: "start consul service"
  systemd:
    state: started
    daemon_reload: yes
    name: consul
    enabled: yes
  become: true
  become_mode: sudo
