---
#install package
- name: yum install docker
  yum: 
    name: ['yum-utils','bridge-utils','device-mapper-persistent-data','lvm2','docker','net-tools']
#  yum: name={{ item }} state=installed
#  with_items:
#    - yum-utils
#    - bridge-utils
#    - device-mapper-persistent-data
#    - lvm2
#    - docker

- name: stop docker
  service: name=docker state=stopped

## check if flannel config file exist
#- name: check flannel config file
#  stat: path=/run/flannel/docker
#  register: p

#- assert:
#    that:
#      - p.stat.exists

# input conf
#- name: input config file
#  template: src=roles/docker/templates/docker.service dest=/usr/lib/systemd/system/docker.service

- name: Check if docker0 exists
  command: "/usr/sbin/ifconfig docker0"
  register: docker0_state
  failed_when: docker0_state.rc not in (0,1)

- name: Configure flanneld to remove default Docker bridge
  shell: "/usr/sbin/ifconfig docker0 down && /usr/sbin/brctl  delbr docker0"
  when: docker0_state.rc == 0

- name: start docker
  systemd: name=docker state=started daemon_reload=yes enabled=yes
