---
# Use this role by root.

#- name: "force add pubkey to localhost"
#  shell: cat /root/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys
#  ignore_errors: True

- name: "check if rsa"
  stat: path=/root/.ssh/{{ item.src }} 
  with_items:
    - { src: id_rsa.pub }
    - { src: id_rsa }
  register: rsa
  delegate_to: localhost
  ignore_errors: True

- name: "install sshpass by apt"
  apt:
    name: sshpass
    state: present
  when: ansible_os_family == 'Debian'
  ignore_errors: True

- name: "create rsa"
  shell: yes y |ssh-keygen -b 2048 -t rsa -f /root/.ssh/id_rsa -q -N ""
  delegate_to: localhost
  when: (rsa.results[0].stat.exists == false) or (rsa.results[1].stat.exists == false)

- name: "install ssh key"
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"

- name: "copy id_rsa.pub"
  copy: src=/root/.ssh/id_rsa.pub dest=/root/.ssh/id_rsa.pub mode=0644

- name: "copy id_rsa"
  copy: src=/root/.ssh/id_rsa dest=/root/.ssh/id_rsa mode=0600

- name: "create known_hosts"
  copy: src=/root/.ssh/known_hosts dest=/root/.ssh/known_hosts mode=0600

- name: "change hostname"
  shell: hostnamectl set-hostname {{hostname|quote}}

- name: "change hosts"
  shell: sed -i "s,`cat /etc/hosts |grep {{ ansible_default_ipv4.address }}  |awk '{print $2}'`,{{ hostname|quote }},g" /etc/hosts

- name: "stop selinux"
  selinux:
    state: disabled

- name: "stop firewalld"
  systemd:
    state: stopped
    daemon_reload: yes
    name: firewalld
    enabled: no
  when: ansible_os_family == 'RedHat'

- name: "stop SuSEfirewall2"
  systemd:
    state: stopped
    daemon_reload: yes
    name: SuSEfirewall2
    enabled: no
  when: ansible_os_family == 'Suse'

- name: "set swap"
  shell: swapoff -a

#- name: set sysctl
#  copy: src=95-k8s-sysctl.conf dest=/etc/sysctl.d/95-k8s-sysctl.conf

#- name: apply sysctl
#  shell: "sysctl -p /etc/sysctl.d/95-k8s-sysctl.conf"
